# Generated by Django 3.1 on 2020-08-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=64, verbose_name='Email')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('country', models.CharField(max_length=5, verbose_name='Страна')),
                ('created_date', models.DateTimeField(db_index=True, verbose_name='Дата регистрации')),
                ('status', models.CharField(blank=True, choices=[('n', 'Not set'), ('a', 'Acquaintances'), ('i', 'Internet'), ('O', 'Outdoor advertising')], default='n', max_length=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_date'],
            },
        ),
    ]
