# Generated by Django 3.1 on 2020-09-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Новый'), ('a', 'Аут'), ('i', 'Не интересно'), ('p', 'Потенциал'), ('d', 'Не отвечает'), ('c', 'Клиент')], default='n', max_length=1, verbose_name='Статус'),
        ),
    ]
