# Generated by Django 3.1 on 2020-09-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0003_lead_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='manager',
        ),
        migrations.AddField(
            model_name='lead',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Менеджер'),
            preserve_default=False,
        ),
    ]
